# NumPy Indexing and Selection

In [4]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

### Bracket Indexing and Selection

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [14]:
arr[0:5] = 100

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] =99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:] =100

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing a 2D array (matrices)

In [29]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[0][0]

5

In [32]:
arr_2d[0]

array([ 5, 10, 15])

In [33]:
arr_2d[1][1]

25

In [34]:
arr_2d[2][1]

40

In [35]:
arr_2d[1,2]

30

In [36]:
arr_2d[1][2]

30

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [47]:
arr_2d[1:,0:]

array([[20, 25, 30],
       [35, 40, 45]])

### Selection
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [48]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
bool_arr = arr > 4

In [51]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr[arr<3]

array([1, 2])

In [55]:
arr_2d =np.arange(50).reshape(5,10)

In [56]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [58]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [60]:
arr_2d[2:4,3:5]

array([[23, 24],
       [33, 34]])