### Numpy Arrays

We can create an array by directly converting a list or list of lists

In [1]:
my_list =[1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np. array(my_list)

In [4]:
arr

array([1, 2, 3])

In [10]:
mymat= [[1,2,3], [4,5,6],[7,8,9]]

In [11]:
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Built-in Methods
There are lots of built-in ways to generate Arrays

#### arange
Return evenly spaced values within a given interval.

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros and ones
Generate arrays of zeros or ones

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### linspace
Return evenly spaced numbers over a specified interval.

In [25]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

#### eye
Creates an identity matrix

In [ ]:
np.eye(3)

#### Random
Numpy also has lots of ways to create random number arrays:

#### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [29]:
np.random.rand(5)

array([0.58881995, 0.91365089, 0.59850593, 0.07384111, 0.75841181])

In [31]:
np.random.rand(5,5)

array([[0.17400956, 0.2855069 , 0.93390086, 0.13279639, 0.01074412],
       [0.43552988, 0.90633222, 0.66620079, 0.14086262, 0.88581253],
       [0.29754909, 0.51748857, 0.4764871 , 0.22422677, 0.90706283],
       [0.76807223, 0.75336882, 0.39697938, 0.14457465, 0.85681153],
       [0.13462132, 0.48546731, 0.89823727, 0.63036784, 0.25701693]])

#### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [32]:
np.random.randn(2)

array([-0.16823624, -2.68976581])

In [56]:
np.random.randn(4,4)

array([[-0.29538997,  0.03967171,  0.32550977, -1.13280741],
       [ 0.36555638, -1.76052682, -1.31777198, -2.07570883],
       [ 0.34520413,  0.56319201, -0.69028895, -1.83789666],
       [ 0.63006272, -0.70270627,  0.46063541,  0.0438564 ]])

#### randint
Return random integers from low (inclusive) to high (exclusive).

In [57]:
np.random.randint(1,100)

5

In [58]:
np.random.randint(1,100)

73

In [59]:
np.random.randint(1,100,10)

array([84, 60, 91, 42, 95, 67,  9, 52, 62, 39])

#### Array Attributes and Methods
Let's discuss some useful attributes and methods or an array:

In [60]:
arr = np.arange(25)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
ranarr = np.random.randint(1,50,10)

In [63]:
ranarr

array([19, 24, 48,  3, 41, 38,  9, 19, 16, 43])

#### Reshape
Returns an array containing the same data with a new shape.

In [64]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
ranarr

array([19, 24, 48,  3, 41, 38,  9, 19, 16, 43])

#### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [66]:
ranarr.max()

48

In [67]:
ranarr.min()

3

In [68]:
ranarr.argmax()

2

In [69]:
ranarr.argmin()

3

#### Shape
Shape is an attribute that arrays have (not a method):

In [70]:
arr.shape

(25,)

In [71]:
arr=arr.reshape(5,5)

In [72]:
arr.shape

(5, 5)

#### dtype
You can also grab the data type of the object in the array:

In [73]:
arr.dtype

dtype('int64')

In [74]:
from numpy.random import randint

In [75]:
randint(2,10)

4